### PR TITLE
MultiKueue: drop the stale remote when a workload finishes OutOfSync

### PR DESCRIPTION
**Pull request by aburan28**
#### What type of PR is this?

/kind bug
/area multikueue

#### What this PR does / why we need it:

A remote workload that finishes with reason `OutOfSync` did not complete the user's Job: it no longer matches the Job it was created for, so it stays `Finished` forever and can never be admitted again.

`reconcileGroup` reset the admission check to `Retry` for that case but left the remote in place, and only did so while the check was still `Ready`. The `Retry` makes the core controller evict the workload, and eviction resets the check to `Pending`, so the check is never `Ready` again. From that point on the stale remote matched on every reconcile and returned early — ahead of the eviction, out-of-sync, admission and nomination steps. The workload kept its quota with the check stuck in `Pending`, and the manager Job was never dispatched to any worker nor finished.

The one path out was the "no quota reservation" cleanup, which only runs if a reconcile happens to observe the window between eviction and re-admission. That is missed whenever the worker is disconnected at that moment, the delete fails, or the events coalesce — so in practice the workload could stay wedged indefinitely.

This PR deletes the `OutOfSync` remotes before deciding what to do with the admission check, so the branch clears itself and the nomination step can dispatch the workload again. A follow-up commit from @YQ-Wang narrows the reset so it fires only when the `OutOfSync` remote is the admitting one, rather than on any remote match.

#### Which issue(s) this PR fixes:

None filed yet — see the note below.

#### Special notes for your reviewer:

- Commit 2 ("Reset the check only when the admitting remote is the OutOfSync one") is authored by @YQ-Wang, who will need to sign the CLA for this PR to go green.
- @tenzen-y asked for an issue describing what was observed in-cluster; that is still outstanding and will be filed separately, since it needs the cluster-side detail rather than just the code analysis above.
- Unit coverage is in `pkg/controller/admissionchecks/multikueue/workload_test.go`; `test/integration/multikueue/jobs_test.go` asserts the stale remote is dropped so the Job can be dispatched again.
- Verified with `go test ./pkg/controller/admissionchecks/multikueue/... -count=1`.
- AI disclosure: this change was prepared with AI assistance and reviewed by the author, per the Kubernetes AI tool usage policy.

#### Does this PR introduce a user-facing change?

```release-note
MultiKueue: Fixed a bug where a remote workload finishing with reason `OutOfSync` left the stale remote in place, wedging the admission check in `Pending`. The workload held its quota indefinitely and the manager Job was neither dispatched to a worker nor finished.
```

### CODE REVIEW

**Comment by tenzen-y** [comment]
@aburan28 Can you sign CLA? Also, can you open an issue to understand what you face in your cluster?

**Comment by aburan28** [comment]
Yes will do

File: pkg/controller/admissionchecks/multikueue/workload.go [hunk 1]
```diff
@@ -656,6 +655,68 @@ func (w *wlReconciler) reconcileGroup(ctx context.Context, group *wlGroup) (reco
...
+	for i, remote := range outOfSyncRemotes {
+		quoted[i] = fmt.Sprintf("%q", remote)
+	}
+	msg := fmt.Sprintf("Remote workload on worker cluster %s is out of sync with its user job, resetting for re-dispatch", stringsutils.Join(quoted, ", "))
+	if err := w.updateACS(ctx, group.local, acs, kueue.CheckStateRetry, msg); err != nil {
+		log.Error(err, "Resetting admission check after remote OutOfSync", "workerClusters", outOfSyncRemotes)
+		return false, err
+	}
+	w.recorder.Eventf(group.local, nil, corev1.EventTypeWarning, "MultiKueue", "MultiKueue", api.TruncateEventMessage(acs.Message))
+	return true, nil
```
[the remark this answers is not in the document]
Comment (aburan28) [reply pkg/controller/admissionchecks/multikueue/workload.go]: This is addressed by @YQ-Wang's follow-up commit "Reset the check only when the admitting remote is the OutOfSync one", which gates the reset on the OutOfSync remote actually being the admitting one, so a Finished `worker2` no longer flips the check to Retry while `worker1` remains admitted.

AI disclosure: this comment was prepared with AI assistance.

**Comment by aburan28** [comment]
@tenzen-y picking this back up, sorry for the delay. Status on your two asks:

**Description** — the PR was opened with the template unfilled; it now has a real description, `/kind bug`, `/area multikueue`, and a release note.

**CI** — `pull-kueue-verify-main` and `pull-kueue-test-integration-multikueue-main` were failing on `test/integration/multikueue/jobs_test.go:232: undefined: apierrors`. That turned out to be a semantic conflict rather than a stale run: main dropped the `apierrors` import from that file while this PR adds new uses of it, so the merge was clean but did not compile. The import is restored and the branch is rebased onto current main (it had drifted ~500 commits). `go vet ./test/integration/multikueue/...` and `go test ./pkg/controller/admissionchecks/multikueue/... -count=1` both pass locally.

**EasyCLA** — one commit was authored as `Claude <noreply@anthropic.com>`, which both trips EasyCLA and conflicts with the no-AI-authorship-marker rule. It is re-authored to me. The remaining blocker is commit 2, authored by @YQ-Wang — that one needs their own CLA signature, and I have deliberately not rewritten their attribution.

**The issue you asked for** — still outstanding. It needs the in-cluster detail of what I actually hit, which I would rather write up properly than approximate from the code, so I will file it separately and link it here.

/retest

AI disclosure: the rebase, the description, and this comment were prepared with AI assistance.

**Comment by aburan28** [comment]
Correction to my previous comment: EasyCLA is now **green**. Re-authoring the `Claude <noreply@anthropic.com>` commit was the only thing blocking it — @YQ-Wang already has a CLA on file, so no action is needed from them. Apologies for the incorrect note.

AI disclosure: prepared with AI assistance.
